/*
 * calculator-backend
 *
 * Calculator backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccountSetup {
    #[serde(rename = "email")]
    pub email: String,
}

impl AccountSetup {
    pub fn new(email: String) -> AccountSetup {
        AccountSetup { email }
    }
}
