/*
 * calculator-backend
 *
 * Calculator backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountState {
    #[serde(rename = "InitialSetup")]
    InitialSetup,
    #[serde(rename = "Normal")]
    Normal,
}

impl ToString for AccountState {
    fn to_string(&self) -> String {
        match self {
            Self::InitialSetup => String::from("InitialSetup"),
            Self::Normal => String::from("Normal"),
        }
    }
}

impl Default for AccountState {
    fn default() -> AccountState {
        Self::InitialSetup
    }
}
