/*
 * calculator-backend
 *
 * Calculator backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Account {
    #[serde(rename = "state")]
    pub state: crate::models::AccountState,
}

impl Account {
    pub fn new(state: crate::models::AccountState) -> Account {
        Account { state }
    }
}
