/*
 * calculator-backend
 *
 * Calculator backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ApiKey : This is just a random string.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApiKey {
    /// API token which server generates.
    #[serde(rename = "api_key")]
    pub api_key: String,
}

impl ApiKey {
    /// This is just a random string.
    pub fn new(api_key: String) -> ApiKey {
        ApiKey { api_key }
    }
}
