/*
 * calculator-backend
 *
 * Calculator backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// AuthPair : AccessToken and RefreshToken

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuthPair {
    #[serde(rename = "access")]
    pub access: Box<crate::models::ApiKey>,
    #[serde(rename = "refresh")]
    pub refresh: Box<crate::models::RefreshToken>,
}

impl AuthPair {
    /// AccessToken and RefreshToken
    pub fn new(access: crate::models::ApiKey, refresh: crate::models::RefreshToken) -> AuthPair {
        AuthPair {
            access: Box::new(access),
            refresh: Box::new(refresh),
        }
    }
}
