/*
 * calculator-backend
 *
 * Calculator backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventToClient {
    #[serde(rename = "AccountStateChanged")]
    AccountStateChanged,
}

impl ToString for EventToClient {
    fn to_string(&self) -> String {
        match self {
            Self::AccountStateChanged => String::from("AccountStateChanged"),
        }
    }
}

impl Default for EventToClient {
    fn default() -> EventToClient {
        Self::AccountStateChanged
    }
}
