/*
 * calculator-backend
 *
 * Calculator backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// RefreshToken : This is just a really long random number which is Base64 encoded.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RefreshToken {
    #[serde(rename = "token")]
    pub token: String,
}

impl RefreshToken {
    /// This is just a really long random number which is Base64 encoded.
    pub fn new(token: String) -> RefreshToken {
        RefreshToken { token }
    }
}
