/*
 * calculator-backend
 *
 * Calculator backend API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SignInWithLoginInfo {
    #[serde(
        rename = "apple_token",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub apple_token: Option<Option<String>>,
    #[serde(
        rename = "google_token",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub google_token: Option<Option<String>>,
}

impl SignInWithLoginInfo {
    pub fn new() -> SignInWithLoginInfo {
        SignInWithLoginInfo {
            apple_token: None,
            google_token: None,
        }
    }
}
